#!/bin/env bash
# grep out what a command argument does
if [ $# -lt 2 ]; 
    then echo "arg <command> <opt> [ lines-before lines-after ]"
    exit
fi

if [ $# -eq 2 ]; 
	then man $1 | grep --color=always  -- $2
	exit
fi

if [ $# -eq 4 ]; 
	then man $1 | grep -B $3 -A $4 --color=always -- $2
	exit
fi

echo "arg <command> <opt> [ lines-before lines-after ]"
