#!/usr/bin/env python3

import pandas
import sys    
import os    
import code    
import argparse    
    
data = []    
try:
	paths=  sys.argv[1:]
except:
	print("Need input path(s)")
	exit(1)
for path in paths:
    data.append(pandas.read_csv(path))
print("{} csv'd data item(s) in variable 'data'.".format(len(data)))
if len(data) == 1:
	data = data[0]
print("Entering interactive mode")
print("=========================")
code.interact(local=locals())     

