#!/usr/bin/env bash
# remove sensitive info from a repo
[ $# -lt 1 ] && echo "Need arg of the file path to purge" && exit 1
arg="$1"
echo "About to purge file [$arg] from git repository based on [$(pwd)], enter 2 continue?"
read -p ""

git filter-branch --force --index-filter "git rm --cached --ignore-unmatch $arg" --prune-empty --tag-name-filter cat -- --all
