#!/usr/bin/env python3

import json    
import sys    
import os    
import code    
import argparse    
    
data = []    
try:
	paths=  sys.argv[1:]
except:
	print("Need input path(s)")
	exit(1)
for path in paths:
	with open(path) as f:    
	    data.append(json.load(f))
print("{} json'd data item(s) in variable 'data'.".format(len(data)))
if len(data) == 1:
	data = data[0]
print("Entering interactive mode")
print("=========================")
code.interact(local=locals())     

