#!/usr/bin/env python3

import json
import sys
import os
import code
import argparse

data = []

def rewrite(path=None):
    if path is None:
        if len(paths) > 0:
            print("Multiple paths")
            return
        path = paths[0]
    with open(path, "w") as f:
        print("Writing to ", f.name)
        json.dump(data, f)

try:
	paths=  sys.argv[1:]
except:
	print("Need input path(s)")
	exit(1)
for path in paths:
	with open(path) as f:
	    data.append(json.load(f))
print("{} json'd data item(s) in variable 'data'.".format(len(data)))
if len(data) == 1:
	data = data[0]
if type(data) == list and type(data[0]) == dict:
    print("Keys:", ", ".join(data[0].keys()) )
print("Entering interactive mode")
print("=========================")
code.interact(local=locals())
