#!/usr/bin/env bash

rclone /home/nik/capture.org dbox:/org/
rclone /home/nik/exercise.org dbox:/org/
rclone /home/nik/life.org dbox:/org/
rclone /home/nik/notes.org dbox:/org/
rclone /home/nik/work/iit/work.org dbox:/org/
rclone /home/nik/work/iit/phd/phd.org dbox:/org/
rclone /home/nik/org/capture.org dbox:/org/
